{
 "title": "GPSD",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Satellite", "query": { "query": "label_values(gpsd_sat_az,prn)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_tpv_mode", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_tpv_time / 1000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Satellites Visible",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_sky_nSat", "legendFormat": "Visible" }
   ]
  },
  {
   "title": "Satellites Used in Nav Solution",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpsd_sky_uSat", "legendFormat": "__auto" }
   ]
  },
  { "title": "Satellites", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Satellite Elevation",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "gpsd_sat_el{prn=~\"$Satellite\"}",
     "legendFormat": "{{ prn }}"
    }
   ]
  },
  {
   "title": "Satellite Azimuth",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "gpsd_sat_az{prn=~\"$Satellite\"}",
     "legendFormat": "{{ prn }}"
    }
   ]
  },
  {
   "title": "Satellite SNR",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dBHz" } },
   "targets": [
    {
     "expr": "gpsd_sat_ss{prn=~\"$Satellite\"}",
     "legendFormat": "{{ prn }}"
    }
   ]
  },
  {
   "title": "Satellite Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpsd_sat_health{prn=~\"$Satellite\"}",
     "legendFormat": "{{ prn }}"
    }
   ]
  },
  {
   "title": "Satellite Use",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpsd_sat_used{prn=~\"$Satellite\"}",
     "legendFormat": "{{ prn }}"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Dilution of Precision (SKY)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "gpsd_sky_gdop", "legendFormat": "Geometric" },
    { "expr": "gpsd_sky_hdop", "legendFormat": "Horizontal" },
    { "expr": "gpsd_sky_pdop", "legendFormat": "Position" },
    { "expr": "gpsd_sky_tdop", "legendFormat": "Time" },
    { "expr": "gpsd_sky_vdop", "legendFormat": "Vertical" },
    { "expr": "gpsd_sky_xdop", "legendFormat": "Longitudinal" },
    { "expr": "gpsd_sky_ydop", "legendFormat": "Latitudinal" }
   ]
  },
  {
   "title": "Errors (TPV)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "gpsd_tpv_epc", "legendFormat": "Climb (m/s)" },
    { "expr": "gpsd_tpv_epd", "legendFormat": "Direction (degrees)" },
    { "expr": "gpsd_tpv_eph", "legendFormat": "2D horizontal position (m)" },
    { "expr": "gpsd_tpv_eps", "legendFormat": "Speed (m/s)" },
    { "expr": "gpsd_tpv_ept", "legendFormat": "Time (s)" },
    { "expr": "gpsd_tpv_epv", "legendFormat": "Vertical (m)" },
    { "expr": "gpsd_tpv_epx", "legendFormat": "Longitude (m)" },
    { "expr": "gpsd_tpv_epy", "legendFormat": "Latitude (m)" }
   ]
  }
 ]
}